version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
      - urnotm:/app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_PRISMA_UR=${DATABASE_URL}
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_HOST=${PGHOST}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PRISMA_UR=${DATABASE_URL}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  urnotm:


